### ISSUE TITLE
React 15 compatibility

### ISSUE THREAD

**Issue by tleunen** [chadoh/react-emoji-picker#3]
Could you please add the React 15 compatibility? Currently, the package is set to work only with React 0.14.

Also, this should be set as a `peerDependency`, not a direct dependency.

**Comment by Sylk** [comment]
Can we get an update on this?

**Comment by Sylk** [comment]
@chadoh

**Comment by tleunen** [comment]
@KrakenEXE You can use `@tleunen/react-emoji-picker`, it supports React 15, but it still uses `React.createClass`. I won't change it because I'm in a process of removing this library from my app anyway, but if you submit a PR in my fork, I'll merge it.

**Comment by chadoh** [comment]
Hey all, sorry to miss this for over an entire year. @tleunen, do you mind submitting a pull request with your improvements?

**Comment by gablabelle** [comment]
@chadoh Don't you simply need to change version number for react in package.json to be compatible with version 14 to 16 ?

https://github.com/chadoh/react-emoji-picker/blob/master/package.json#L22

**Comment by chadoh** [comment]
Sorry, everyone, I am no longer using this package. I have switched https://entire.life to using [emoji-mart](https://github.com/missive/emoji-mart), and have even contributed an improvement over there. It's all-around a better and more up-to-date emoji picker, and I highly recommend switching to it. I'll add some info to the README to let others know.
